#!/usr/bin/env bash
set -euo pipefail
home="$(realpath "$(realpath "${BASH_SOURCE[0]}" | xargs dirname)"/.)"
cd "$home"

npm link ~/jzr/intershop-intertext
npm link ~/jzr/svgttf
npm link ~/jzr/fontmirror


